- packages/account-abstraction/src/BiconomyPaymasterAPI.ts
- packages/account-abstraction/src/ERC4337EthersProvider.ts
- packages/account-abstraction/src/ERC4337EthersSigner.ts
- packages/account-abstraction/src/HttpRpcClient.ts
- packages/account-abstraction/src/Provider.ts
- packages/account-abstraction/src/utils/httpRequests.ts
- packages/core-types/src/smart-account.types.ts
- packages/relayer/src/rest-relayer.ts
- packages/smart-account/src/SmartAccount.ts
verifying service updates + dappAPIKey metadata in httpRpcClient + error handling in client messanger (without url in config) + headers in util request
> verifying service for singleton Biconomy Paymaster

- packages/core-types/src/SmartAccountTypes.ts
- packages/smart-account/src/SmartAccount.ts
Debug flag added in smart account logging + signer getter
To silence unnecessary logs optional debug flag has been added which is by default false.
Demo dapp
NA for transactions
> debug flag added in smart account logging + signer getter

- packages/web3-auth/src/SocialLogin.tsx
- packages/web3-auth/src/types/Web3AuthConfig.ts
- Refactor the SocialLogin package
No need to call the `showConnectModal()` method.
The SocialLogin class now expects zero default parameters.
You may any one of these if needed
```ts
{
chainId: string
whitelistUrls: { [P in string]: string }
network: 'mainnet' | 'testnet'
}
```
Tested with the examples and sdk demo package.
> social login refactor

- packages/web3-auth/src/SocialLogin.tsx
- packages/web3-auth/src/UI.tsx
- packages/web3-auth/src/types/Web3AuthConfig.ts
Added a new optional param whiteLabel solution for clients who needs it.
Added a new method to export private key which can be exposed to users.
> feat: whiteLabel and private key method

- packages/node-client/README.md
- packages/smart-account/README.md
* Hardware:
* Toolchain:
* SDK:
> Read me/release/1.0.0

- packages/account-abstraction/src/ERC4337EthersProvider.ts
- packages/account-abstraction/src/ERC4337EthersSigner.ts
* Hardware:
* Toolchain:
* SDK:
> fix(erc4337): add engine checker

- package.json
- packages/web3-auth/src/SocialLogin.tsx
Currently if someone closes the modal gets the error from web3Auth and crashes the app.
Locally via demo dapp
> Feat web3auth error handling

- packages/relayer/src/utils/HttpRequests.ts
- packages/smart-account/src/SmartAccount.ts
- packages/transactions/src/TransactionManager.ts
This PR includes following changes
1. Gas Estimation removal in Fallback flow and using constant gasLimit
2. getNetworkConfig fix as it was not async call before
3. Delegate call fix in Fallback flow
4.  hardcode gasLimit removal as we want relayer to estimate and send trx using that
5. Added Some Logging
> some fixes

- packages/account-abstraction/src/BaseAccountAPI.ts
- packages/account-abstraction/src/BiconomyPaymasterAPI.ts
- packages/account-abstraction/src/ERC4337EthersProvider.ts
- packages/account-abstraction/src/ERC4337EthersSigner.ts
- packages/account-abstraction/src/FallbackGasTankAPI.ts
- packages/account-abstraction/src/HttpRpcClient.ts
- packages/account-abstraction/src/Provider.ts
- packages/account-abstraction/src/SmartAccountAPI.ts
- packages/account-abstraction/src/UserOperationEventListener.ts
- packages/account-abstraction/src/WalletFactoryAPI.ts
- packages/common/src/Logger.ts
- packages/core-types/src/SmartAccountTypes.ts
- packages/relayer/package.json
- packages/relayer/src/FallbackRelayer.ts
- packages/relayer/src/LocalRelayer.ts
- packages/relayer/src/RestRelayer.ts
- packages/relayer/src/utils/HttpRequests.ts
- packages/smart-account/src/SmartAccount.ts
- packages/smart-account/src/providers/SmartAccountProvider.ts
- packages/transactions/package.json
- packages/transactions/src/ContractUtils.ts
- packages/transactions/src/Estimator.ts
- packages/transactions/src/TransactionManager.ts
- packages/transactions/src/Utils.ts
- Use one Logger to console all logs.
- Use the env variable to enable the logs
- Use [consoleColors.js](https://gist.github.com/abritinthebay/d80eb99b2726c83feb0d97eab95206c4) to improve logs readability.
> feat: improve logs

- packages/account-abstraction/src/SmartAccountAPI.ts
- packages/common/src/ERC4337Utils.ts
- packages/core-types/src/ChainsTypes.ts
feeData specific changes
* Hardware:
* Toolchain:
* SDK:
> handle eip1559 unsupported networks

- packages/core-types/src/SmartAccountTypes.ts
- packages/node-client/src/types/NodeClientTypes.ts
- packages/smart-account/src/SmartAccount.ts
- packages/transactions/src/TransactionManager.ts
- packages/transactions/src/Types.ts
Change skip estimation logic from env to dto.
Now skipEstimation flag can be passed in dto of createUserPaidTransaction and createUserPaidTransactionBatch function
> skipEstimation added in dto

- packages/account-abstraction/src/ERC4337EthersSigner.ts
- packages/account-abstraction/src/SmartAccountAPI.ts
- packages/core-types/src/evm-manager/EvmNetworkManager.ts
PR includes fixes for bundler estimation endpoint
Good to merge post testing
* Hardware:
* Toolchain:
* SDK:
> fixes for bundler estimation endpoint

- packages/particle-auth/CHANGELOG.md
- packages/particle-auth/package.json
* Hardware:
* Toolchain:
* SDK:
> chore: finalise package version for publishing particle-auth

- packages/web3-auth-native/src/SocialLogin.ts
- packages/web3-auth-native/src/index.ts
- packages/web3-auth-native/src/types/sdk.ts
Fixed all `Soical` in web3-auth-native package to `Social`
- [x ] Typo cleanup
Local testing and search
> fix: clean web3-auth-native

- packages/web3-auth-native/src/SocialLogin.ts
fixes lint issue in web3-auth-native social login 
* Hardware:
* Toolchain:
* SDK:
> fix: linting issue in social login

- packages/account-abstraction/package.json
- packages/common/CHANGELOG.md
- packages/common/package.json
- packages/core-types/CHANGELOG.md
- packages/core-types/package.json
- packages/ethers-lib/package.json
- packages/node-client/package.json
- packages/particle-auth/CHANGELOG.md
- packages/particle-auth/package.json
- packages/relayer/CHANGELOG.md
- packages/relayer/package.json
- packages/smart-account/CHANGELOG.md
- packages/smart-account/package.json
- packages/transactions/CHANGELOG.md
- packages/transactions/package.json
* Hardware:
* Toolchain:
* SDK:
> chore: version bump for necessary packages + changelog

- packages/account/src/SmartAccount.ts
- packages/paymaster/src/BiconomyPaymaster.ts
- packages/paymaster/src/interfaces/IHybridPaymaster.ts
- packages/paymaster/src/interfaces/IPaymaster.ts
- packages/paymaster/src/utils/Types.ts
+ update interfaces
* Hardware:
* Toolchain:
* SDK:
> feat: update responses to support calculateGasLimits flag 

- .gitignore
- README.md
- packages/transak/package.json
- packages/web3-auth-native/package.json
* Hardware:
* Toolchain:
* SDK:
> update versions and README

- packages/account/src/BiconomySmartAccount.ts
- packages/account/src/SmartAccount.ts
https://github.com/bcnmy/biconomy-client-sdk/issues/236 
* Hardware:
* Toolchain:
* SDK:
> fix: avoid sending populated values of gas prices when estimating 

- README.md
I replaced the broken Readme link to the correct one
it opens up normally in a markdown previewer
> fix: update broken docs link

- packages/account/src/BiconomySmartAccountV2.ts
- packages/account/src/utils/Constants.ts
- packages/account/src/utils/Types.ts
- packages/modules/src/BaseValidationModule.ts
- packages/modules/src/ECDSAOwnershipValidationModule.ts
- packages/modules/src/SessionKeyManagerModule.ts
- packages/modules/src/interfaces/IValidationModule.ts
- packages/modules/src/utils/Constants.ts
- packages/modules/src/utils/Types.ts
* Hardware:
* Toolchain:
* SDK:
> session manager module init + dev notes + module versions

- packages/modules/src/BaseValidationModule.ts
- packages/modules/src/SessionKeyManagerModule.ts
- packages/modules/src/interfaces/ISessionStorage.ts
- packages/modules/src/utils/Types.ts
Updates the #258 PR remediations needed
> fix: session manager changes

- packages/account/src/BiconomySmartAccountV2.ts
- packages/account/src/utils/Types.ts
- rebuild.sh
* Hardware:
* Toolchain:
* SDK:
> setters for validation modules + refactor

- packages/account/src/BiconomySmartAccountV2.ts
Added isModuleEnabled method in BiconomySmartAccountV2
> Add isModuleEnabled method

- packages/account/src/BaseSmartAccount.ts
- packages/account/src/BiconomySmartAccountV2.ts
- packages/account/src/interfaces/IBaseSmartAccount.ts
- packages/account/src/utils/Types.ts
- packages/modules/src/BaseValidationModule.ts
- packages/modules/src/ECDSAOwnershipValidationModule.ts
- packages/modules/src/MultichainValidationModule.ts
- packages/modules/src/SessionKeyManagerModule.ts
- packages/modules/src/interfaces/IValidationModule.ts
- packages/modules/src/utils/Types.ts
* Hardware:
* Toolchain:
* SDK:
> init with dev notes

- packages/account/src/BiconomySmartAccountV2.ts
- packages/account/src/utils/Constants.ts
- packages/account/src/utils/Types.ts
2D nonce support + Manual nonce override support in case anyone needs it!
* Hardware:
* Toolchain:
* SDK:
> init with nonce options for account V2

- CONTRIBUTING.md
I've updated the contributing.md file for contribution
> 📝 add contributing.md

- packages/account/src/BiconomySmartAccountV2.ts
- packages/account/tests/SmartAccountV2.local.spec.ts
- packages/modules/src/ECDSAOwnershipValidationModule.ts
- packages/modules/src/MultichainValidationModule.ts
* Hardware:
* Toolchain:
* SDK:
> all instances use create pattern

- packages/account/src/BaseSmartAccount.ts
- packages/account/src/BiconomySmartAccount.ts
- packages/account/src/BiconomySmartAccountV2.ts
- packages/account/src/utils/Constants.ts
- packages/account/tests/SmartAccountV2.local.spec.ts
- packages/bundler/src/utils/Types.ts
- packages/common/src/ContractsInstances.ts
- packages/modules/src/BaseValidationModule.ts
- packages/modules/src/BatchedSessionRouterModule.ts
- packages/modules/src/ECDSAOwnershipValidationModule.ts
- packages/modules/src/MultichainValidationModule.ts
- packages/modules/src/SessionKeyManagerModule.ts
- packages/modules/src/utils/Constants.ts
- packages/modules/src/utils/Types.ts
- packages/node-client/src/INodeClient.ts
- packages/node-client/src/types/NodeClientTypes.ts
- packages/paymaster/src/BiconomyPaymaster.ts
- packages/paymaster/src/utils/Types.ts
* Hardware:
* Toolchain:
* SDK:
> address todo and review comments

- packages/account/CHANGELOG.md
- packages/account/package.json
- packages/bundler/CHANGELOG.md
- packages/bundler/package.json
- packages/common/CHANGELOG.md
- packages/common/package.json
- packages/core-types/CHANGELOG.md
- packages/core-types/package.json
- packages/modules/CHANGELOG.md
- packages/modules/package.json
- packages/node-client/CHANGELOG.md
- packages/node-client/package.json
- packages/particle-auth/CHANGELOG.md
- packages/particle-auth/package.json
- packages/paymaster/CHANGELOG.md
- packages/paymaster/package.json
- packages/transak/CHANGELOG.md
- packages/transak/package.json
- packages/web3-auth-native/CHANGELOG.md
- packages/web3-auth-native/package.json
- packages/web3-auth/CHANGELOG.md
- packages/web3-auth/package.json
* Hardware:
* Toolchain:
* SDK:
> Release r5

- packages/account/tests/SmartAccountV2.local.spec.ts
* Hardware:
* Toolchain:
* SDK:
> add delay in/after beforeAll

- packages/account/package.json
- packages/account/src/BiconomySmartAccountV2.ts
- packages/account/src/index.ts
- packages/account/src/utils/VoidSigner.ts
- packages/account/tests/SmartAccountV2.local.spec.ts
> Add void signer to support smart account address overrides 

- packages/node-client/README.md
- packages/node-client/src/types/NodeClientTypes.ts
balance can be checked for any address and not just eoa or smart account address.
> update eoaAddress -> address in Balances Dto

- packages/modules/src/SessionKeyManagerModule.ts
> default storage client

- packages/account/src/BaseSmartAccount.ts
- packages/account/src/BiconomySmartAccount.ts
- packages/account/src/BiconomySmartAccountV2.ts
- packages/account/src/SmartAccount.ts
- packages/bundler/src/Bundler.ts
- packages/common/src/Utils.ts
use undefined in place of ! + check on limits returned by paymaster and throw
> fix: misleading error when paymaster policy check fails 

- .gitignore
- packages/account/src/BiconomySmartAccountV2.ts
- packages/paymaster/src/BiconomyPaymaster.ts
- Updating the bundler abstraction for v4
- Fixed the token paymaster bigint error throw
- gitignore update
> fix: bundler abstraction in v4

- packages/account/package.json
- packages/account/src/BiconomySmartAccountV2.ts
- packages/account/src/provider.ts
- packages/account/src/utils/Logger.ts
- packages/bundler/src/utils/HttpRequests.ts
- packages/bundler/src/utils/Logger.ts
- packages/modules/src/MultichainValidationModule.ts
- packages/modules/src/utils/Logger.ts
- packages/paymaster/src/BiconomyPaymaster.ts
- packages/paymaster/src/utils/HttpRequests.ts
- packages/paymaster/src/utils/Logger.ts
Instead of adding a new package for adding logger in all packages, let's reuse the Logger class.
> Feat: Add Logger

- packages/modules/src/interfaces/ISessionStorage.ts
- packages/modules/src/session-storage/SessionLocalStorage.ts
- packages/modules/src/utils/Types.ts
Viem does not give access to signer.private key like ethers.Wallet had so this function needed to be changed.
> Update addSigner method inside SessionLocalStorage.ts

- packages/account/src/BiconomySmartAccountV2.ts
> Changed parameter name

- .github/workflows/docs.yml
- .gitignore
- packages/account/package.json
- packages/account/src/BiconomySmartAccountV2.ts
- packages/account/typedoc.json
Added docs using tsdoc
Related Issue: SMA-526
> Resolved SMA-526

- .husky/pre-commit
- package.json
Removed lint-staged because it was causing some unexpected issue.
> Removed lint-staged

- .gitignore
All files inside sessionStorageData should be ignore but not the folder itself.
> Except sessionStorageData folder from gitignore but not files

- packages/modules/package.json
- packages/modules/src/MultichainValidationModule.ts
- packages/modules/src/SessionKeyManagerModule.ts
- yarn.lock
> Fixed merkletreejs import

- packages/account/src/utils/Types.ts
Commented overrides and skipBundlerGasEstimation params
> Commented overrides and skipBundlerGasEstimation params

- packages/account/package.json
- packages/account/src/BiconomySmartAccountV2.ts
- packages/account/tests/account.e2e.spec.ts
- packages/account/tests/account.spec.ts
- packages/bundler/package.json
- packages/common/package.json
- packages/common/src/utils/EthersSigner.ts
- packages/modules/package.json
- packages/modules/tests/utils/customSession.ts
- packages/paymaster/package.json
- tests/setup-e2e-tests.ts
- tests/setup-unit-tests.ts
- yarn.lock
> V4 with viem v2 (bump aa-core and viem)

- packages/bundler/src/Bundler.ts
- packages/common/src/utils/HttpRequests.ts
- packages/common/src/utils/Types.ts
- packages/paymaster/src/BiconomyPaymaster.ts
- yarn.lock
Added a new param to sendRequest() called "service". The new param will let us know from which service is the sendRequest called.
> Added a new param to sendRequest "service"

- packages/account/package.json
- packages/account/src/index.ts
- packages/bundler/CHANGELOG.md
- packages/bundler/Readme.md
- packages/bundler/package.json
- packages/bundler/src/Bundler.ts
- packages/bundler/src/index.ts
- packages/bundler/src/utils/Types.ts
- packages/common/package.json
- packages/common/src/utils/Types.ts
- packages/modules/package.json
- packages/particle-auth/package.json
- packages/paymaster/CHANGELOG.md
- packages/paymaster/Readme.md
- packages/paymaster/package.json
- packages/paymaster/src/BiconomyPaymaster.ts
- packages/paymaster/src/index.ts
- packages/paymaster/src/utils/Types.ts
- packages/transak/package.json
export createBundler and createPaymaster for the sake of consistency
> Make package exports consistent

- packages/account/package.json
- packages/bundler/package.json
- packages/common/package.json
- packages/modules/CHANGELOG.md
- packages/modules/package.json
- packages/particle-auth/CHANGELOG.md
- packages/particle-auth/package.json
- packages/paymaster/package.json
- packages/transak/CHANGELOG.md
- packages/transak/package.json
- yarn.lock
> Release 8 - Biconomy V4 SDK

- packages/account/tests/account.e2e.spec.ts
- packages/bundler/tests/bundler.e2e.spec.ts
- packages/modules/tests/multiChainValidationModule.e2e.spec.ts
- packages/paymaster/tests/paymaster.e2e.spec.ts
- tests/chains.config.ts
> Replaced baseGoerli with baseSepolia

- packages/account/src/index.ts
- packages/account/src/utils/Types.ts
- packages/bundler/CHANGELOG.md
- packages/modules/src/BatchedSessionRouterModule.ts
- packages/modules/src/utils/Types.ts
- packages/modules/tests/ecdsaValidationModule.e2e.spec.ts
- yarn.lock
Added simple e2e tests for ecdsa module
Related Issue: #SMA-604
- [] I've updated the documentation if necessary
- Added very simple test for ecdsa module
> Chore(SMA-604): ecdsa tests

- .gitignore
- packages/account/CHANGELOG.md
- packages/account/package.json
- packages/account/src/index.ts
- packages/account/tests/account.spec.ts
- packages/bundler/package.json
- packages/common/package.json
- packages/common/src/utils/EthersSigner.ts
- packages/modules/package.json
- packages/modules/src/BaseValidationModule.ts
- packages/modules/src/BatchedSessionRouterModule.ts
- packages/modules/src/ECDSAOwnershipValidationModule.ts
- packages/modules/src/MultichainValidationModule.ts
- packages/modules/src/SessionKeyManagerModule.ts
- packages/particle-auth/package.json
- packages/paymaster/package.json
- packages/transak/package.json
- yarn.lock
Fixes the issue raised here: https://github.com/alchemyplatform/aa-sdk/issues/472
Related Issue: SMA-673
> Fix(SMA-673): RPC provider CORS issue

- packages/common/src/utils/HttpRequests.ts
- packages/paymaster/src/BiconomyPaymaster.ts
Fixed incorrect log in BiconomyPaymaster.ts and refactor error log message.
> Fixed logs

- packages/account/src/BiconomySmartAccountV2.ts
- packages/account/src/utils/Types.ts
- packages/bundler/src/Bundler.ts
- packages/bundler/src/interfaces/IBundler.ts
- packages/common/src/utils/Types.ts
- yarn.lock
Added StateOverrideSet parameter in SDK.
Todo's:
- add test cases
More about StateOverrideSet:
- https://www.libevm.com/2022/01/12/advance-geth-pt-2-stateoverrides/
> Added StateOverrideSet parameter

- packages/account/package.json
- packages/bundler/package.json
- packages/common/package.json
- packages/modules/package.json
- packages/particle-auth/CHANGELOG.md
- packages/particle-auth/package.json
- packages/particle-auth/src/index.ts
- packages/paymaster/package.json
- packages/transak/package.json
- yarn.lock
Particle Auth not correctly exporting some classes
Related Issue: SMA-677
> Fix(SMA-677): Particle auth build broken

- packages/account/src/BiconomySmartAccountV2.ts
- packages/account/src/utils/Types.ts
- packages/account/tests/account.e2e.spec.ts
- packages/paymaster/src/utils/Types.ts
Added new helper method on the Smart Account which return an array  of supported tokens from the erc20 paymaster associated with the Smart Account
```
const tokens = await smartAccount.getSupportedTokens();
// Returns:
[
{
symbol: "USDC",
tokenAddress: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
decimal: 6,
logoUrl: "https://assets.coingecko.com/coins/images/279/large/usd-coin.png?1595353707",
premiumPercentage: 0.1,
}
]
```
Related Issue: SMA-597
> Feat(SMA-597): Supported Tokens method

- packages/account/src/BiconomySmartAccountV2.ts
- packages/account/src/utils/Types.ts
- packages/paymaster/src/utils/Types.ts
> added flag to skip calldata approval patch

- .github/workflows/docs.yml
- packages/account/src/BiconomySmartAccountV2.ts
- packages/account/src/utils/Types.ts
- packages/account/tests/account.spec.ts
- packages/bundler/src/Bundler.ts
- packages/bundler/src/utils/Types.ts
- tests/utils.ts
- yarn.lock
Supports custom chains
```
const customBlastChain = {
id: 81_457,
name: "Blast",
//   network: "blast",
nativeCurrency: {
decimals: 18,
name: "Ethereum",
symbol: "ETH",
},
rpcUrls: {
public: { http: ["https://rpc.blast.io"] },
default: { http: ["https://rpc.blast.io"] },
},
blockExplorers: {
etherscan: { name: "Blastscan", url: "https://blastscan.io/" },
default: { name: "Blastscan", url: "https://blastscan.io/" },
},
contracts: {
multicall3: {
address: "0xca11bde05977b3631167028862be2a173976ca11",
blockCreated: 88_189,
},
},
} as const satisfies Chain;
const {
whale: { privateKey },
} = ganache;
const accountOne = privateKeyToAccount(privateKey);
const walletClientWithCustomChain = createWalletClient({
account: accountOne,
chain: customBlastChain,
transport: …
```
> Support custom chains

- packages/account/src/BiconomySmartAccountV2.ts
- packages/account/src/utils/Utils.ts
Minor improvement around the dx of the getBalance call. It will now always return the native token balance in the response.
> Improved balances

- yarn.lock
> Back merge main branch

- .github/ISSUE_TEMPLATE/bug_report.yml
> fix: bug report

- packages/account/src/BiconomySmartAccountV2.ts
- packages/account/src/abi/SmartAccount.ts
- packages/account/tests/account.e2e.spec.ts
- packages/account/tests/account.read.e2e.spec.ts
- packages/account/tests/account.spec.ts
- yarn.lock
> added 1271 support + tests

- src/bundler/utils/Constants.ts
- tests/account/write.test.ts
> chore: skip transfer tests
