bcnmy/biconomy-client-sdk

packages/web3-auth/src/UI.tsx
There is a warning on the console when using the current SVG properties syntax.
=> updated SVG dom properties

packages/account-abstraction/src/ERC4337EthersSigner.ts, packages/smart-account/src/SmartAccount.ts, packages/transactions/src/ContractUtils.ts
Remove deploy wallet only from aa signer and add a flag + ret type in smart account
SDK demo fails with below if you try to do deployWalletUsingPaymaster and had no return type
```
TransactionNotifier.ts:83 TypeError: Cannot read properties of undefined (reading 'emit')
at TransactionNotifier.onMined (ERC4337EthersProvider.ts:174:1)
at TransactionNotifier.transactionNotifierMessageHandler (TransactionNotifier.ts:71:1)
at Subscription.emit (events.js:153:1)
at Centrifuge._handlePublication (centrifuge.js:1579:1)
at Centrifuge._handlePush (centrifuge.js:1596:1)
at Centrifuge._dispatchReply …
```
=> gasless deploy wallet only 

packages/core-types/src/SmartAccountTypes.ts, packages/smart-account/src/SmartAccount.ts
signTransactionDto requires mandatory version and chainId which should be ideally optional
sendSignedTransaction method expects gasLimit which is optional, but if not passed then relay endpoint fails 
update dto type
update default gas limit / omit
with demo dapps
=> fix: signTransaction and sendSignedTransaction dto fixes

packages/relayer/src/LocalRelayer.ts, packages/relayer/src/RestRelayer.ts, packages/smart-account/src/SmartAccount.ts
smartAccount.sendTransaction accepts SendTransactionDto and dispatches to relayer.relay which accepts RelayTransactionDto. GasLimit is optional in both of these Dtos but within RestRelayer.relay it passed on gasLimit.hex whatsoever. This PR fixes above bug that broke the code
Fixture in making gasLimit truly optional
Testing Notes: 
gasLimit truly optional for sendTransaction.  after changes : if I don’t provide custom gas limit it works but internal ten fails with BSA010   require(gasleft() >= max((_tx.targetTxGas * 64) / 63,_tx.targetTxGas + 2500) + 500, "BSA010");
This is because of gasLimit calculated in relayer and targetTxGas estimated and sent!  failed without custom gasLimit - https://mumbai.polygonscan.com/tx/0xaee78c4d6b5d340d00292d01c546cfbeabf3fe370664e677615091 …
=> fix:make gas limit really optional

packages/account-abstraction/src/ERC4337EthersProvider.ts
For dispatching AA transaction on chain via bundler, ERC4337Provider [constructs](https://github.com/bcnmy/biconomy-client-sdk/blob/master/packages/account-abstraction/src/ERC4337EthersProvider.ts#L163) a response (type TransactionResponse) 
[ Note: The hash you get from txResponse is not the transaction hash but requestId ] 
For above response, wait() is supposed to return receipt Promise<TransactionReceipt> in which transaction hash must be transactionHash. Currently it is captured in receipt.hash hence on the client side type any has to be used and by capturing receipt.hash which is wrong. This change fixes types in receipt and makes it transactionHash...
Further notes : WIP to get recept.transactionHash from upstream (which is messaging sdk / transaction listener service.) cc …
=> fix: tx receipt from messaging sdk + dev notes

packages/account-abstraction/src/BiconomyPaymasterAPI.ts, packages/account-abstraction/src/ClientConfig.ts, packages/account-abstraction/src/SmartAccountAPI.ts, packages/core-types/src/AccountAbstractionTypes.ts, packages/smart-account/src/SmartAccount.ts
feat/strictSponsorshipMode and fix/BiconomyPaymasterAPI edge case + dev notes + update type
* added strictSponsorshipMode field in ClientConfig
* made constructor of BiconomyPaymasterAPI to just take one argument as object
* based on strictSponsorshipMode (default value currently false and dapps can't pass) and if signingService fails we will return '0x' so the wallet can self sponsor
* if account still doesnt have funds it should fail from bundler service with proper error code / message
[ signing service never returns other statusCode than 200 or message and always throws which is something we can look into @arcticfloyd1984  @talhamalik883 ] 
Please describe the tests that you ran to verify your changes. Provide instructions …
=> Signing service negative case (allow wallet self sponsor)

packages/account-abstraction/src/BaseAccountAPI.ts, packages/smart-account/src/SmartAccount.ts
Hardware wallet like ledger or MPC wallet signers like Portal sends v value 0 or 1 in signature. This fixes v value to be either 27 or 28 (1b or 1c)
Also checks if signature doesn't start with 0x then append 0x.
* Hardware:
* Toolchain:
* SDK:
=> fix invalid v value in userop signature

packages/common/src/httpRequests.ts, packages/paymaster/src/BiconomyPaymaster.ts, packages/paymaster/src/utils/Types.ts
… + add strict mode
update @biconomy/common package httpUtils which is used to handle jsonRpc Only response and error types from Bundler and Paymaster nodes. 
Added strict Mode flag in Biconomy Paymaster, default value of which will be true.
* Hardware:
* Toolchain:
* SDK:
=> error handling in paymaster 

packages/account/src/BiconomySmartAccount.ts, packages/account/src/SmartAccount.ts, packages/bundler/src/Bundler.ts, packages/paymaster/src/BiconomyPaymaster.ts, packages/paymaster/src/interfaces/IHybridPaymaster.ts, packages/paymaster/src/interfaces/IPaymaster.ts
This PR passing required userOp params for bundler estimation and removal of dummy userOp values
=> fix userOp estimate gas overrides

packages/account/CHANGELOG.md, packages/account/package.json, packages/bundler/CHANGELOG.md, packages/bundler/package.json, packages/common/CHANGELOG.md, packages/common/package.json, packages/core-types/CHANGELOG.md, packages/core-types/package.json, packages/node-client/CHANGELOG.md, packages/node-client/package.json, packages/particle-auth/CHANGELOG.md, packages/particle-auth/package.json, packages/paymaster/CHANGELOG.md, packages/paymaster/package.json, packages/web3-auth-native/CHANGELOG.md, packages/web3-auth-native/package.json, packages/web3-auth/CHANGELOG.md, packages/web3-auth/package.json
* Hardware:
* Toolchain:
* SDK:
=> bump package version and add changelog

packages/account/src/BiconomySmartAccount.ts
An RPC call is made to verify whether the smart account is deployed when the nonce is zero. We previously implemented logic to include initCode in userOp only when the nonce is zero. However, we discovered a scenario where someone might have deployed the smart account on your behalf, resulting in a nonce of zero. In this case, the initCode should not be added to userOp.
=> verify account deployment even when nonce is 0

packages/account/src/BiconomySmartAccount.ts, packages/account/src/SmartAccount.ts
finalUserOp passed to calculateUserOpGasValues function is replaced with userOp that has overrides gas attributes
=> finalUserOp replaced with userOp for overrides proper usage

packages/account/CHANGELOG.md, packages/account/package.json, packages/bundler/CHANGELOG.md, packages/bundler/package.json, packages/common/CHANGELOG.md, packages/common/package.json, packages/common/src/ERC4337Utils.ts, packages/core-types/CHANGELOG.md, packages/core-types/package.json, packages/node-client/package.json, packages/paymaster/CHANGELOG.md, packages/paymaster/package.json
* Hardware:
* Toolchain:
* SDK:
=> Publish alpha.1

packages/modules/src/interfaces/ISessionStorage.ts
* Hardware:
* Toolchain:
* SDK:
=> Adding Session Storage Interface

packages/modules/src/session-storage/SessionLocalStorage.ts
* Hardware:
* Toolchain:
* SDK:
=> Adding Session Local storage class

packages/modules/src/BaseValidationModule.ts, packages/modules/src/SessionKeyManagerModule.ts, packages/modules/src/session-storage/SessionLocalStorage.ts, packages/modules/src/utils/Types.ts, packages/modules/src/utils/Uid.ts
SessionKeyManagerModule implementation
```ts
const biconomyAccount = new BiconomySmartAccount();
const biconomySessionManager = await SessionKeyManagerModule.create();
const sessionKeyData = await createSessionData({
validUntil: 0,
validAfter: 0,
sessionValidationModuleAddress: "0xeeee address of module (eg: erc20)",
sessionKeyData: "0xabc data",
});
const tx = {
to: await biconomyAccount.address,
data: sessionKeyData,
value: 0,
}
const partialUserOp = await biconomySmartAccount.buildUserOp([tx]);
const userOpResponse = await biconomySmartAccount.sendUserOp(partialUserOp);
// after success tx set the sessionKey in the session manager
if(userOpResponse.status === "success") {
await biconomySessionManager.setSessionKey(sessionKey);  
}
```
```ts
const biconomyAccount = new …
```
=> Session Key Manager module implementation

packages/modules/src/SessionKeyManagerModule.ts
Fixes the issue reported by rage trade. `ethers/lib/utils` keccak256 returns the 32 bytes output on getHexRoot.
> maybe affected by https://github.com/merkletreejs/merkletreejs/issues/86 or same as https://github.com/merkletreejs/merkletreejs/issues/33 ?
=> fix: incorrect data merkleRoot length

packages/modules/src/SessionKeyManagerModule.ts, packages/modules/src/interfaces/ISessionStorage.ts, packages/modules/src/session-storage/SessionLocalStorage.ts
Adding merkle root in session storage when a new session is created and stored in the storage.
=> Set merkle root in session storage while creating session

packages/modules/src/SessionKeyManagerModule.ts
As per https://github.com/bcnmy/scw-contracts/blob/SCW-V2-Modular-SA/contracts/smart-account/modules/SessionKeyManagerModule.sol#L79-L86 merkleProof should be getHexProof of keccack256 of leaf
not test extensively, just matched specs with contract
* Hardware:
* Toolchain:
* SDK:
=> use proof instead of root in signUserOpHash

packages/account/CHANGELOG.md, packages/account/package.json, packages/bundler/CHANGELOG.md, packages/bundler/package.json, packages/common/CHANGELOG.md, packages/common/package.json, packages/core-types/CHANGELOG.md, packages/core-types/package.json, packages/node-client/CHANGELOG.md, packages/node-client/package.json, packages/particle-auth/CHANGELOG.md, packages/particle-auth/package.json, packages/paymaster/CHANGELOG.md, packages/paymaster/package.json, packages/transak/CHANGELOG.md, packages/transak/package.json, packages/web3-auth-native/CHANGELOG.md, packages/web3-auth-native/package.json, packages/web3-auth/CHANGELOG.md, packages/web3-auth/package.json
3.0.0 series (modular sdk stable)
* Hardware:
* Toolchain:
* SDK:
=> update changelog and package version

packages/account/src/BiconomySmartAccountV2.ts, packages/account/src/utils/Types.ts
in buildUserOp even if transactions array length is 1, for some validation modules optionally devs want to encode it for executeBatch. optional flag is added which achieves this
* Hardware:
* Toolchain:
* SDK:
=> buildUserOp: force encode for batch

packages/modules/src/BatchedSessionRouterModule.ts
* Hardware:
* Toolchain:
* SDK:
=> Sma 121 batched router dummysig

packages/account/src/BaseSmartAccount.ts, packages/account/tests/SmartAccountV2.local.spec.ts
The BaseSmartAccount has isDeployed variable in cache, and it stores it on constructor init as default false then read.
It is never updated, so either can updated but in other methods but then will have to add logic if tx is failed or not.
Best way is to remove this check and call rpc to check if deployed or not everytime
=> fix: gitInitCode cache issue

packages/account/package.json, packages/account/src/BaseSmartAccount.ts, packages/account/src/BiconomySmartAccountV2.ts, packages/account/src/SmartAccount.ts, packages/account/src/utils/Types.ts, packages/bundler/src/Bundler.ts, packages/bundler/src/interfaces/IBundler.ts, packages/bundler/src/utils/Types.ts, packages/modules/src/utils/Types.ts, packages/node-client/README.md
If someone wants to have this call data check on their end for every transaction we have enabled more parameters in our eth_sendUserOperation to pass in a simulation_type an example curl for this: https://gist.github.com/arcticfloyd1984/26efb6099efc651d2cf064340c67c6db.
=> add simulation type param

packages/account/src/utils/Types.ts
Made "entryPointAddress" optional as it is handled in the SDK if not provided by user.
Related Issue: # DEVX-350
=> Made entryPointAddress optional

packages/bundler/src/Bundler.ts, packages/bundler/src/utils/Constants.ts
Added conditional logic for situations when user will not provide "entryPointAddress" to the Bundler.
Related Issue: #
=> Added check for entryPointAddress field

packages/account/Readme.md, packages/account/src/BiconomySmartAccountV2.ts, packages/account/src/utils/Types.ts, packages/account/tests/account.e2e.spec.ts, packages/account/tests/account.spec.ts, packages/account/tests/index.d.ts, packages/bundler/tests/index.d.ts, packages/paymaster/tests/index.d.ts, setup-e2e-tests.ts, setup-unit-tests.ts
This PR facilitates the use of viems' `walletClient` as the signer while instantiating the smartWallet. 
Previously:
```
import {  WalletClientSigner } from "@alchemy/aa-core";
import { createSmartWalletClient } from "@biconomy/account"
const aaWalletClientSigner = new WalletClientSigner(viemWalletClient, "viem");
const smartWallet = await createSmartWalletClient({ chainId, signer:  aaWalletClientSigner})
```
Now:
```
import { createSmartWalletClient } from "@biconomy/account"
const smartWallet = await createSmartWalletClient({ signer:  viemWalletClient})
```
The chainId is now inferred from viem's walletClient
Related Issue: DEVX-405
Resolved: DEVX-422
This PR abstracts away AAs WalletClientSigner, so that viems' walletClient can be used as the signer instead.
We're doing work in the …
=> AA WalletClientSigner Abstraction

packages/common/src/utils/Types.ts
Added a helper interface in order to support signer type from ethersV6.
=> Add ethersV6 compatibility

packages/account/src/BiconomySmartAccountV2.ts, yarn.lock
Fix check for maxApproval in BiconomySmartAccountV2
=> Fix check for maxApproval in BiconomySmartAccountV2

packages/modules/src/BatchedSessionRouterModule.ts, packages/modules/src/SessionKeyManagerModule.ts, packages/modules/src/utils/Types.ts, packages/modules/tests/sessionValidationModule.e2e.spec.ts
Currently the sessionSigner is expected to be of type SmartAccountSigner, which is unpleasant DX. This changes the type to: SupportedSigner and handles the appropriate cases where alternative signers are provided
- [] Breaking Change
=> Change type: sessionSigner: SupportedSigner

linkAll.sh, packages/account/package.json, packages/account/src/BiconomySmartAccountV2.ts, packages/account/src/utils/Constants.ts, packages/account/tests/account.e2e.spec.ts, packages/bundler/package.json, packages/common/package.json, packages/modules/package.json, packages/particle-auth/package.json, packages/paymaster/package.json, packages/transak/package.json
This PR allows for the following bare-bones params to be accepted, returning a list of quotes for supported tokens on the chain / paymaster
```
{ paymasterServiceData: { mode: PaymasterMode.ERC20 } }
```
=> Feat(SMA-579): Allow empty tokenInfo fields during getTokenFees

.github/workflows/docs.yml, packages/account/src/BiconomySmartAccountV2.ts, yarn.lock
Internal docs are currently down. Alchemy's deprecated class was the problem, some infinite recursion was causing jsdoc to crash. ignoring accountContract & entryPoint from the docs fixes the problem. This solution can stay in place until we remove alchemy's base class
Related Issue: SMA-682
=> fix(SMA-682): Fix docs

packages/account/CHANGELOG.md, packages/account/src/index.ts, packages/account/src/utils/Constants.ts, packages/account/src/utils/Utils.ts, packages/account/tests/utils.spec.ts, yarn.lock
Added a getChain helper which retrieves the list of chains we support out of the box. 
```
const chain = getChain(chainId);
```
Allows users to dynamically find the chain that they are using, so context can be switched quickly/easily using the chainId alone. 
Solves [this issue](https://biconomyworkspace.slack.com/archives/C05HA4DU12P/p1709217302299989), with [this solution
](https://biconomyworkspace.slack.com/archives/C066X6E3J9Y/p1708686664755669)
=> Add getChain helper

packages/account/src/BiconomySmartAccountV2.ts, yarn.lock
The check for user op nonce field was wrong, if nonce is passed as 0 (number or BigInt) the validateUserOp function will throw an error, as 0 is a falsy value. 
Fix: Replaced the logical NOT operator with isNullOrUndefined utility method.
=> Fix wrong falsy check for user op nonce

src/bundler/utils/Utils.ts
Our SDK was hard coded to expect a v2 URL version.
This PR aims to allow upcoming v3 version for Nexus
=> fix: update parsing of the bundler url from config
